name: hackrf_flutter
description: "A Flutter plugin for interfacing with HackRF devices. Supports Android platform."
version: 0.0.1
homepage: https://github.com/SarahRoseLives/hackrf_flutter
repository: https://github.com/SarahRoseLives/hackrf_flutter
issue_tracker: https://github.com/SarahRoseLives/hackrf_flutter/issues
documentation: https://github.com/SarahRoseLives/hackrf_flutter#readme
publish_to: "https://pub.dev"

environment:
  sdk: ^3.8.1
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  plugin:
    platforms:
      android:
        package: com.example.hackrf_flutter
        pluginClass: HackrfFlutterPlugin

# Optional: Uncomment and add if you have assets or fonts
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg

# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700